config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "configuration#index"
    get "/calculate_tutors_required" => 'configuration#calculate_num_tutors', as: 'calculate_tutors_required'

    post "/hourly_rates" => "hourly_rates#update", as: "hourly_rates_update"
    post "/deadline" => "configuration#deadline", as: "deadline"
    post "/tutor_hours" => "configuration#tutor_hours", as: "tutor_hours"
    post "/course_hours" => "configuration#course_hours", as: "course_hours"
    post "/year_and_term" => "configuration#year_and_term", as: "year_and_term"
    put  "/import_courses" => "configuration#import_courses", as: "import_courses"
    resources :hourly_rates, only: [:index] do
    end
  end

  get 'courses/:id/export_course' => 'courses#export_course', :as => 'export_course'
  get 'courses/export_all_courses' => 'courses#export_all_courses', :as => 'export_all_courses'
  patch 'courses/:id/calculate_tutors' => 'courses#calculate_required_tutors', as: 'calculate_required_tutors'
  patch 'courses/:id/propose_course' => 'courses#propose_course', as: 'propose_course'
  patch 'courses/:id/finalise_accepted' => 'courses#finalise_accepted', as: 'finalise_accepted'
  get "/courses/:id/get_no_required_tutors" => 'courses#get_no_required_tutors', as: 'required_tutors'
  resources :courses, only: [:index, :show, :update]

  get "login" => "sessions#new", :as => "login"
  post 'login' => 'sessions#create', :as => 'post_session'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'users#new', :as => 'signup'

  resources :users, :only => [:create, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  root "application#home_page"

  patch 'tutor_applications/:id/update_comment' => 'tutor_applications#update_comment', :as => 'update_comment'
  patch 'tutor_applications/:id/disqualify_tutor' => 'tutor_applications#disqualify_tutor', as: 'disqualify_tutor'

  get 'tutor_applications/:id/application_print' => 'tutor_applications#application_print', :as => 'print_application'
  get 'tutor_applications/export_finalised_tutors' => 'tutor_applications#export_finalised_tutors', :as => 'export_finalised_tutors'
  get 'tutor_applications/export_all_tutors' => "tutor_applications#export_all_tutors", :as => 'export_all_tutors'

  resources :tutor_applications, except: [:delete]
  get "/tutor_applications" => "tutor_applications#index", as: 'tutor_applications_filter'
  patch "/tutor_applications/:id/update_pay" => "tutor_applications#update_pay", as: 'tutor_application_update_pay'

  post "/allocation_link/:application_id" => "allocation_link#create", as: "create_allocation"
  put "/allocation_link/:id/update_state" => "allocation_link#update_state", as: "update_allocation_state"
  post "/accept/:id" => "allocation_link#accept", as: "accept_allocation"
  post "/reject/:id" => "allocation_link#reject", as: "reject_allocation"

  resources :allocation_link, only: [:destroy]

end

app/controllers/tutor_applications_controller.rb
class TutorApplicationsController < ApplicationController

  include ActionView::Helpers::NumberHelper

  #before_action :authorize_tm, only: [:index, :tutor_list_xls, :application_print, :update_pay, :disqualify_tutor]
  #before_action :authorize_tm_or_cc, only: [:show, :update_comment]
  #before_action :authorize_tm_or_student, only: [:update, :edit, :create, :new]

  # anyone logged in
  def new
    if Date.today > Admin::Configuration.deadline
      render :deadline_passed and return
    end
    @application = TutorApplication.where(student_ID: current_user.student_ID)
    if @application.any?
      redirect_to edit_tutor_application_path(@application.first)
    end
    @tutor_application = TutorApplication.new
  end

  # anyone logged in
  def create
    render :deadline_passed and return if before_deadline?

    @tutor_application = TutorApplication.new(tutor_application_params)
    if @tutor_application.save
      if current_user.TM?
        redirect_to tutor_applications_path, :notice => 'Application created'
      else
        redirect_to edit_tutor_application_path(@tutor_application), :notice => 'Application created'
      end
     else
      render :new
    end
  end

  #TM only
  def index
    if params[:filters]
      @tutor_applications = TutorApplication.current_applications
      @tutor_applications = @tutor_applications.select do |application|
        keep = false
        @filters = params[:filters].split(" ")
        @filters.each do |filter|
          keep = true if application.tags.any?{|tagarray| tagarray[0].match(filter)}
        end
        keep
      end
    else
      @tutor_applications = TutorApplication.current_applications
    end
  end

  #TM and CC and student
  def show
    @tutor_application = TutorApplication.find(params[:id])
    @courses = Course.all.sort_by{|c| @tutor_application.suitability_for_course(c)}.reverse
    @allocation_links = @tutor_application.allocation_links
    if current_user.CC? && !@allocation_links.any? { |al| al.course.course_coordinator_id == current_user.id }
      redirect_to login_path, :notice => 'You are not authorised.' and return
    end
    find_grades
    if @tutor_application.allocation_links.allocated.size > 2
      flash.now[:error] = "Tutor is allocated to more than 2 courses."
    end
  end

  def application_print
    @tutor_application = TutorApplication.find(params[:id])
    find_grades
    render layout: false
  end

  # TM and student
  def edit
    @tutor_application = TutorApplication.find(params[:id])
    if current_user.student? && @tutor_application.student_ID != current_user.student_ID
      redirect_to root_path
    end
  end

  # TM and student
  def update
    render :deadline_passed, status: 423 and return if before_deadline?
    @tutor_application = TutorApplication.find(params[:id])
    if @tutor_application.update(tutor_application_update_params)
      if current_user.TM?
        redirect_to tutor_application_path(@tutor_application), :notice => 'Application updated'
      else
        redirect_to edit_tutor_application_path(@tutor_application), :notice => 'Application updated'
      end

    else
      render :edit, :notice => 'Application update failed'
    end
  end

  def update_pay
    render :deadline_passed, status: 423  and return if before_deadline?
    @tutor_application = TutorApplication.find(params[:id])
    update = {years_experience: tutor_application_update_params[:years_experience], pay_level: tutor_application_update_params[:pay_level]}
    if @tutor_application.update(update)
      render json: { pay_rate: number_to_currency(@tutor_application.reload.pay_rate), scholarship: !!@tutor_application.vuw_doctoral_scholarship? }
    else
      head 400
    end
  end

  #TM and CC
  def update_comment
    @tutor_application = TutorApplication.find(params[:id])
    if @tutor_application.update(comment_param)
      redirect_to tutor_application_path(@tutor_application), :notice => 'Comment updated'
    else
      render :show, :notice => 'Comment update failed'
    end
  end

  def disqualify_tutor
    @tutor_application = TutorApplication.find(params[:id])
    @tutor_application.disqualify
    redirect_to tutor_application_path(@tutor_application), :notice => 'Application Disqualifed'
  end

  #TM only
  def export_all_tutors
    @tutor_applications = TutorApplication.current_applications


    #symbols = @tutor_applications.column_names.map(&:to_sym).reject{|k| k.to_sym == :id}
    symbols = [:first_name, :last_name, :gender, :student_ID, :ecs_email, :private_email, :mobile_number,
      :home_phone, :preferred_hours, :enrolment_level, :qualifications, :first_choice, :second_choice, :previous_non_tutor_vuw_contract,
      :previous_tutor_experience, :other_information, :vuw_doctoral_scholarship, :teaching_qualification,
      :comment, :year, :term, :tutor_training, :years_experience, :created_at, :updated_at]
    keys = []

    tutors = []
    symbols.each do |sym|
      keys.push TutorApplication.field_to_name(sym)
    end

    @tutor_applications.each do |application|
      tutors.push(application.to_xls)
    end

    tempfile = Tempfile.new("test.xls")
    book = ExcelExport.export_tutor_list({keys: keys, tutors: tutors})
    book.write(tempfile.path)
    send_file tempfile.path, filename: "test.xls"
  end

  def export_finalised_tutors
    filename = 'test_finalised.xls'
    tempfile = Tempfile.new(filename)
    book = ExcelExport.export_finalised_tutors AllocationLink.allocated
    book.write tempfile.path
    send_file tempfile.path, filename: filename
  end

  private

  def comment_param
    params.require(:tutor_application).permit(:comment)
  end

  def tutor_application_params
    params.require(:tutor_application).permit(:first_name, :last_name, :student_ID, :ecs_email,
      :private_email, :mobile_number, :home_phone, :preferred_hours, :enrolment_level,
      :qualifications, :first_choice_id, :second_choice_id, :previous_non_tutor_vuw_contract,
      :previous_tutor_experience, :other_information, :vuw_doctoral_scholarship, :gender, :photo, :transcript,
      :tutor_training, :teaching_qualification)
  end

  def tutor_application_update_params
    params.require(:tutor_application).permit(:first_name, :last_name,
      :private_email, :mobile_number, :home_phone, :preferred_hours, :enrolment_level,
      :qualifications, :first_choice_id, :second_choice_id, :previous_non_tutor_vuw_contract,
      :previous_tutor_experience, :other_information, :vuw_doctoral_scholarship, :gender, :photo, :transcript,
      :tutor_training, :pay_level, :years_experience, :teaching_qualification)
  end

  def grades_to_array_with_suitability(tutor_application, grades)
    grades = tutor_application.get_grades
    out_grades = []
    grades.each do |k,v|
      out_grades << OpenStruct.new(course_code: k, grade: v, suitability: Suitability.suitability_rating(@tutor_application.suitability_for_course(Course.where(course_code: k).first)))
    end
    out_grades
  end

  def find_grades
    Suitability.where(tutor_application_id: @tutor_application.id).each{|s| s.delete}
    @tutor_application.calculate_suitability

    @grades = grades_to_array_with_suitability(@tutor_application, @tutor_application.get_grades())
  end

  def before_deadline?
    Date.today > Admin::Configuration.deadline
  end
end

app/helpers/tutor_application_helper.rb
module TutorApplicationHelper
  #temporary stuff
  def get_grades()

    # courses = ["SWEN300", "SWEN301", "SWEN302", "SWEN303", "ENGL301", "COMP103", "COMP102", "SWEN222"]
    # numcourses = Course.count

    courses = []
    grades = ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "E", "WD", "K"]

    constant_random = Random.new(student_ID.hash)
    Course.all.each do |course|
      courses << course.course_code
    end

    temporary_number = constant_random.rand(grades.count)

    persons_grades = {}

    courses.each do |course|
      random_number = constant_random.rand(5) - 5
      b = temporary_number + random_number
      b = 12 if b > 12
      b = 0 if b < 0

      persons_grades[course] = grades[b]

    end

    return persons_grades
  end

  def value_of_grade(gradestring)
    {
      "A+"  => 9,
      "A"   => 8,
      "A-"  => 7,
      "B+"  => 6,
      "B"   => 5,
      "B-"  => 4,
      "C+"  => 3,
      "C"   => 2,
      "C-"  => 1
    }[gradestring] || 0
  end
end

app/views/tutor_applications/_course_row.html.erb
<% @this_grade = grades.select{|g| g.course_code == course.course_code }.first %>
<% @al = AllocationLink.where(tutor_application_id: @tutor_application.id, course_id: Course.where(course_code: @this_grade.course_code).first).first %>
<tr>
  <td><%= link_to course.course_code, course %></td>
  <td><%= @this_grade.grade  %></td>
  <td>
    <span class='label label-<%= Suitability.suitability_label_name(@this_grade.suitability) %>'>
      <%= Suitability.suitability_name(@this_grade.suitability) %>
    </span>
  </td>
  <td>
    <%= render partial: 'layouts/allocation_state', locals: { :allocation => @al } %>
  </td>
</tr>

app/views/tutor_applications/application_print.html.erb
<!-- <%=  image_tag(@tutor_application.photo.url(:medium), class: "img-thumbnail", style: "max-width: 125px; height:auto;") %>-->

<strong> First Name: </strong><%= @tutor_application.first_name %>
<br />
<strong> Last Name: </strong><%= @tutor_application.last_name %>
<br />

<strong> Student ID: </strong><%= @tutor_application.student_ID %>
<br />
<strong> <%= TutorApplication.field_to_name(:gender) %>: </strong><%= @tutor_application.gender %>
<br />
<strong> ECS Email: </strong><%= @tutor_application.ecs_email %>
<br />
<strong> Private Email: </strong><%= @tutor_application.private_email %>



<br /><strong> Mobile Number: </strong><%= @tutor_application.mobile_number %><br /><strong> NZ Phone Number: </strong><%= @tutor_application.home_phone %>



<br /><strong> First Choice: </strong><%= @tutor_application.first_choice.course_code %>
<br /><strong> Second Choice: </strong><%= @tutor_application.second_choice.course_code %>


<br /><strong> VUW Doctoral Scholarship: </strong><%= @tutor_application.vuw_doctoral_scholarship %><br /><strong> Preferred Hours Per Week: </strong><%= @tutor_application.preferred_hours %>



<br /><strong> Qualifications/Degrees Completed: </strong><%= @tutor_application.qualifications %><br /><strong> Enrolment Level: </strong><%= @tutor_application.enrolment_level %>



<br /><strong> Previous Non-Tutor Contract with VUW: </strong><%= @tutor_application.previous_non_tutor_vuw_contract %>


<br /><strong> Previous Tutoring Experience: </strong><%= @tutor_application.previous_tutor_experience %>


<br /><strong> Other Information: </strong><%= @tutor_application.other_information %>



<br /><Strong> Comments: </Strong><%= @tutor_application.comment %>


<br /><strong>Grades:</strong>
<table class="table">
  <tbody>
    <% @grades.each_slice(2).with_index do |slice, i| %>
      <tr>
        <% slice.each do |grade| %>
          <td><%= grade.course_code %></td>
          <td>
            <span class='label label-<%= Suitability.suitability_label_name(grade.suitability) %>'>
              <%= Suitability.suitability_name(grade.suitability) %>
            </span>
          </td>
          <td><%= grade.grade %></td>
          <td width=300 />
        <% end %>
        <% if i == 0 %>
          <tr><td colspan="3"/></tr>
        <% end  %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/tutor_applications/deadline_passed.html.erb
<div class='alert alert-danger'>The deadline has passed for applications. Click <%= link_to "here", :back %> to go back.</div>

app/views/tutor_applications/edit.html.erb
<h1>Tutor Application form</h1>
<%= semantic_form_for @tutor_application do |f| %>
  <%= f.inputs do %>

  <div class="row">
    <div class="col-md-4">
        <%= f.input :first_name, required: true, label:  "First Name: "  %>
    </div>
    <div class="col-md-4">
        <%= f.input :last_name, required: true, label:  "Last Name: " %>
    </div>
    <div class="col-md-2">
        <%= f.input :gender, as: :select, collection: TutorApplication.genders, required: true, label: TutorApplication.field_to_name(:gender) %>
    </div>
    <div class="col-md-2">
        <%= f.input :student_ID, required: true, label:  "Student ID Number: " %>
    </div>
  </div>

    <div class="row">
        <div class="col-md-6">
            <%= f.input :ecs_email, required: true, label:  "ECS Email: " %>
        </div>
        <div class="col-md-6">
            <%= f.input :private_email, required: true, label:  "Private Email: " %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <%= f.input :mobile_number, required: true, label:  "Mobile Number: " %>
        </div>
        <div class="col-md-6">
            <%= f.input :home_phone, label:  "NZ Phone Number: " %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <%= f.input :preferred_hours, label:  "Preferred hours per week: ", as: :string %>
        </div>
        <div class="col-md-3">
        <%= f.input :enrolment_level, as: :select, collection: TutorApplication.enrolment_level, label:  "Enrolment when trimester starts: ", include_blank: false %>
        </div>
        <div class="col-md-3">
            <%= f.input :qualifications, as: :select, collection: TutorApplication.qualifications, label:  "Qualifications/Degrees completed: ", include_blank: false %>
        </div>
        <div class="col-md-3">
            <%= f.input :tutor_training, as: :select, collection: TutorApplication.tutor_training, label: "Tutor Training: ", include_blank: false %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <%= f.input :first_choice, required: true, member_label: :course_code, include_blank: false %>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <%= f.input :second_choice, required: true, member_label: :course_code, include_blank: false %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5">
            <%= f.input :photo, label: "Upload Photo", hint: "This photo is optional. If you upload a photo, you agree that we can use the image on the course webpage." %>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <%= f.input :transcript, label: "Upload Transcript", hint: "If you have not studied at VUW, please provide an Academic Transcript in PDF form." %>
        </div>
    </div>

    <%# <%= f.input :first_choice, required: true, as: :select, collection: TutorApplication.courses, label:  "First choice course to tutor: " %1> %>

    <%# <%= f.input :second_choice, required: true, as: :select, collection: TutorApplication.courses, label:  "Second choice course to tutor: ", hint: "If you want to change these courses after allocation started, email the senior tutor. We will try to allocate you to your 1st or 2nd choice, but we may have to place you elsewhere where you are most needed" %1> %>

    <%= f.input :previous_non_tutor_vuw_contract, input_html: {rows: 8}, label:  "Previous non-tutor Contract with VUW: ", hint: "If you had any non-tutor fixed term contract with VUW in ANY school, in the last 6 months please provide the School name, start date and end date" %>



    <%= f.input :previous_tutor_experience, input_html: {rows: 8}, label:  "Previous tutoring experience: ", hint: "Course/Year/Trimester" %>

    <%= f.input :other_information, input_html: {rows: 8}, label:  "Other Information: ", hint: "e.g. Date you can start if you are not able to start from beginning of trimester" %>

    <div class"row">
        <div class="col-md-3">
            <%= f.input :vuw_doctoral_scholarship, as: :radio, label:  "Do you have a VUW Doctoral Scholarship: " %>
        </div>
        <div class="col-md-3">
            <%= f.input :teaching_qualification, as: :radio, label:  "Teaching Qualification: " %>
        </div>
    </div>

  <% end %>
  <%= f.actions %>
<% end %>

app/views/tutor_applications/index.html.erb
<table class='table' id='table'>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Student ID</th>
      <th>First Choice</th>
      <th>Second Choice</th>
      <th>Previous Experience</th>
      <th>Qualifications</th>
      <th>VUW Doctoral Scholarship?</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
    <% @tutor_applications.each do |ta| %>
      <tr class='table_row_hover' data-url='<%= tutor_application_path(ta) %>'>
        <td><%= ta.first_name %></td>
        <td><%= ta.last_name %></td>
        <td><%= ta.student_ID %></td>
        <td><%= ta.first_choice.course_code %></td>
        <td><%= ta.second_choice.course_code %></td>
        <td><%= ta.previous_tutor_experience.present? ? 'yes' : 'no' %></td>
        <td><%= ta.qualifications %></td>
        <td><%= ta.vuw_doctoral_scholarship ? "Yes" : "No" %></td>
        <td>
          <% ta.tags.each do |tag| %>
            <span class="label label-<%= tag[1] %>"><%= tag[0] %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<div class='row'>
  <div class='col-md-3'>
    <%= link_to "Export All Tutors", :export_all_tutors, class: "btn btn-xs btn-primary" %>
    <%= link_to "Export Finalised Tutors", :export_finalised_tutors, class: "btn btn-xs btn-primary" %>
  </div>
  <div class='col-md-2'></div>
  <div class='col-md-7'>
    <div class='btn-group pull-right'>
      <%= link_to "Disqualified", "#", class: "filter_button btn btn-sm btn-danger" %>
      <%= link_to "Unallocated", "#", class: "filter_button btn btn-sm btn-default" %>
      <%= link_to "Planned", "#", class: "filter_button btn btn-sm btn-info" %>
      <%= link_to "Reserve", "#", class: "filter_button btn btn-sm btn-default" %>
      <%= link_to "Shortlisted", "#", class: "filter_button btn btn-sm btn-warning" %>
      <%= link_to "Accepted", "#", class: "filter_button btn btn-sm btn-primary" %>
      <%= link_to "Rejected", "#", class: "filter_button btn btn-sm btn-danger" %>
      <%= link_to "Allocated", "#", class: "filter_button btn btn-sm btn-success" %>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= form_tag(tutor_applications_filter_path, method: :get) do |f| %>
          <%= hidden_field_tag "filters", @filters.blank? ? TutorApplication.tags : @filters %>
          <%= submit_tag "Update filters", class: "filter btn btn-sm btn-primary pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tutor_applications/show.html.erb
<div class="row">

  <div class="col-md-3">

    <p>
      <strong> First Name: </strong><%= @tutor_application.first_name %>
    </p>
    <p>
      <strong> Last Name: </strong><%= @tutor_application.last_name %>
    </p>

    <p>
      <strong> <%= TutorApplication.field_to_name(:gender) %>: </strong><%= @tutor_application.gender %>
    </p>

    <p>
      <strong> Student ID: </strong><%= @tutor_application.student_ID %>
    </p>

    <p>
      <strong> Tutor Training: </strong><%= @tutor_application.tutor_training %>
    </p>
  </div>
  <div class="col-md-4">
    <p>
      <strong> ECS Email: </strong><%= @tutor_application.ecs_email %>
    </p>
    <p>
      <strong> Private Email: </strong><%= @tutor_application.private_email %>
    </p>
    <p>
      <strong> Mobile Number: </strong><%= @tutor_application.mobile_number %>
    </p>
    <p>
      <strong> NZ Phone Number: </strong><%= @tutor_application.home_phone %>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <strong> First Choice: </strong><%= @tutor_application.first_choice.course_code %>
    </p>
    <p>
      <strong> Second Choice: </strong><%= @tutor_application.second_choice.course_code %>
    </p>
    <p>
      <strong> VUW Doctoral Scholarship: </strong><%= @tutor_application.vuw_doctoral_scholarship %>
    </p>
    <p>
      <strong> Teaching Qualification: </strong><%= @tutor_application.teaching_qualification %>
    </p>
  </div>

  <div class="col-md-2">
    <%= image_tag(@tutor_application.photo.url(:medium), class: "img-thumbnail", style: "max-width: 125px; height:auto;") %>
  </div>
</div>
<br />

<div class="row">
  <div class="col-md-3">
    <p>
      <strong> Preferred Hours Per Week: </strong><%= @tutor_application.preferred_hours %>
    </p>
  </div>
  <div class="col-md-4">
    <p>
      <strong> Qualifications/Degrees Completed: </strong><%= @tutor_application.qualifications %>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <strong> Enrolment Level: </strong><%= @tutor_application.enrolment_level %>
    </p>
  </div>
  <div class="col-md-2">
    <div class='btn-group-vertical'>
    <%if @tutor_application.transcript_file_name? %>
      <%= link_to "Download Transcript", @tutor_application.transcript.url, class: 'btn btn-xs btn-success', style: "width:125px;" %>
    <% else %>
      <%= link_to "No Transcript", "#", class: "btn btn-xs btn-default disabled", style: "width: 125px" %>
    <% end %>
    <%= link_to "Print", print_application_path(@tutor_application), class: "btn btn-xs btn-primary", style: "width: 125px" %>
    <% if current_user.TM? %>
      <%= link_to "Disqualify Tutor", disqualify_tutor_path, class: 'btn btn-xs btn-success', :method => :patch %>
    <% end %>
    </div>
  </div>
</div>
<br />



<p>
  <strong> Previous Non-Tutor Contract with VUW: </strong><%= @tutor_application.previous_non_tutor_vuw_contract %>
</p>
<p>
  <strong> Previous Tutoring Experience: </strong><%= @tutor_application.previous_tutor_experience %>
</p>
<p>
  <strong> Other Information: </strong><%= @tutor_application.other_information %>
</p>

<p>
  <%= @tutor_application.suitability_string %>
  <br />
  Suitability of > 6 is excellent, > 4 is good, > 2 is ok, > 0 is bad <= 0 is unsuitable
</p>

<br />

<div class='row'>
  <div class='col-md-8'>
    <strong>Grades and Allocations:</strong>
    <table class='table table-striped'>
      <thead>
        <th>Course</th>
        <th>Grade</th>
        <th>Suitability</th>
        <th>State</th>
      </thead>
      <tbody>
      <%= render partial: "course_row", locals: { course: @tutor_application.first_choice, grades: @grades } %>
      <%= render partial: "course_row", locals: { course: @tutor_application.second_choice, grades: @grades } %>
      <% @grades.reject{|g| [@tutor_application.first_choice.course_code, @tutor_application.second_choice.course_code].include? g.course_code}.sort_by{|c| [c.course_code.last(3), c.course_code]}.each do |grade| %>
        <%= render partial: "course_row", locals: { course: Course.where(course_code: grade.course_code).first, grades: @grades } %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class='col-md-4'>
    <div class="hidden-sm" style="height: 55px;"></div>
    <div class='well'>
      <strong>Pay rate: </strong><span id='pay_rate'><%= "#{number_to_currency(@tutor_application.try(:pay_rate))} #{" (Scholarship)" if !!@tutor_application.vuw_doctoral_scholarship?}" %></span><span id='pay_rate_status' style='display:none; padding-left: 10px;'></span>
      <br />
      <br />
      <%= semantic_form_for(@tutor_application, remote: true, url: tutor_application_update_pay_path(@tutor_application), html: { id: "update_pay_form"} ) do |f| %>
        <%= f.input :years_experience, as: :select, collection: [0,1,2,3], include_blank: false %>
        <%= f.input :pay_level, as: :select, collection: Admin::HourlyRates::levels_form, include_blank: false %>
        <%= f.actions do %>
          <%= f.action :submit, button_html: { value: "Update", class: "btn btn-primary pull-right" } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class='row'>
  <div class='col-md-12'>
    <%= semantic_form_for @tutor_application, url: update_comment_path do |f| %>
    <%= f.inputs do %>
      <%= f.input :comment, input_html: {rows: 8}, label:  "Comment: "  %>
    <% end %>
      <%= f.actions %>
    <% end %>
  </div>
</div>