config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "configuration#index"
    get "/calculate_tutors_required" => 'configuration#calculate_num_tutors', as: 'calculate_tutors_required'

    post "/hourly_rates" => "hourly_rates#update", as: "hourly_rates_update"
    post "/deadline" => "configuration#deadline", as: "deadline"
    post "/tutor_hours" => "configuration#tutor_hours", as: "tutor_hours"
    post "/course_hours" => "configuration#course_hours", as: "course_hours"
    post "/year_and_term" => "configuration#year_and_term", as: "year_and_term"
    put  "/import_courses" => "configuration#import_courses", as: "import_courses"
    resources :hourly_rates, only: [:index] do
    end
  end

  get 'courses/:id/export_course' => 'courses#export_course', :as => 'export_course'
  get 'courses/export_all_courses' => 'courses#export_all_courses', :as => 'export_all_courses'
  patch 'courses/:id/calculate_tutors' => 'courses#calculate_required_tutors', as: 'calculate_required_tutors'
  patch 'courses/:id/propose_course' => 'courses#propose_course', as: 'propose_course'
  patch 'courses/:id/finalise_accepted' => 'courses#finalise_accepted', as: 'finalise_accepted'
  get "/courses/:id/get_no_required_tutors" => 'courses#get_no_required_tutors', as: 'required_tutors'
  resources :courses, only: [:index, :show, :update]

  get "login" => "sessions#new", :as => "login"
  post 'login' => 'sessions#create', :as => 'post_session'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'users#new', :as => 'signup'

  resources :users, :only => [:create, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  root "application#home_page"

  patch 'tutor_applications/:id/update_comment' => 'tutor_applications#update_comment', :as => 'update_comment'
  patch 'tutor_applications/:id/disqualify_tutor' => 'tutor_applications#disqualify_tutor', as: 'disqualify_tutor'

  get 'tutor_applications/:id/application_print' => 'tutor_applications#application_print', :as => 'print_application'
  get 'tutor_applications/export_finalised_tutors' => 'tutor_applications#export_finalised_tutors', :as => 'export_finalised_tutors'
  get 'tutor_applications/export_all_tutors' => "tutor_applications#export_all_tutors", :as => 'export_all_tutors'

  resources :tutor_applications, except: [:delete]
  get "/tutor_applications" => "tutor_applications#index", as: 'tutor_applications_filter'
  patch "/tutor_applications/:id/update_pay" => "tutor_applications#update_pay", as: 'tutor_application_update_pay'

  post "/allocation_link/:application_id" => "allocation_link#create", as: "create_allocation"
  put "/allocation_link/:id/update_state" => "allocation_link#update_state", as: "update_allocation_state"
  post "/accept/:id" => "allocation_link#accept", as: "accept_allocation"
  post "/reject/:id" => "allocation_link#reject", as: "reject_allocation"

  resources :allocation_link, only: [:destroy]

end

app/models/admin/configuration.rb
module Admin
  class Configuration < ActiveRecord::Base
    validates_presence_of :key, :value
    validate :check_deadline_is_date
    validate :check_year_and_term
    validate :check_tutor_hours
    validate :check_course_multipliers

    def self.deadline
      Date.parse(where(key: "deadline").first.try(:value) || '1970-01-01')
    end

    def self.deadline=(val)
      date = find_or_initialize_by(key: "deadline")
      date.value = val.is_a?(Date) ? val.to_s : val
      date.save
    end

    def self.tutor_hours
      where(key: "tutor_hours").first.try(:value).try(:to_i) || 70
    end

    def self.set_tutor_hours(val)
      field = find_or_initialize_by(key: "tutor_hours")
      field.value = val
      field.save
    end

    def self.course_hours(level)
      where(key: "course_hours_#{level}_level").first.try(:value).to_i || 4
    end

    def self.set_course_hours(level, val)
      field = find_or_initialize_by(key: "course_hours_#{level}_level")
      field.value = val
      field.save
    end

    def self.year
      (where(key: "year").first.try(:value) || 1970).to_i
    end

    def self.set_year(val)
      year = find_or_initialize_by(key: "year")
      year.value = val ? val.to_s : val
      year.save
    end

    def self.term
      (where(key: "term").first.try(:value) || 1).to_i
    end

    def self.set_term(val)
      term = find_or_initialize_by(key: "term")
      term.value = val ? val.to_s : val
      term.save
    end

    private

    def check_deadline_is_date
      if key == "deadline"
        begin
          Date.parse(value)
        rescue
          errors.add(:base, "Date is invalid")
        end
      end
    end

    def check_year_and_term
      if key == "year"
        if !is_num?(value)
          errors.add(:base, "Year is invalid")
        end
      end
      if key == "term"
        if !is_num?(value)
          errors.add(:base, "Term is invalid")
        else
          errors.add(:base, "Term is invalid") if ![1,2,3].include? value.to_i
        end
      end
    end

    def check_tutor_hours
      if key == "tutor_hours"
        if !is_num?(value)
          errors.add(:base, "not numeric")
        end
      end
    end

    def check_course_multipliers
      required = ["course_hours_100_level", "course_hours_200_level", "course_hours_300_level", "course_hours_400_level"]
      if required.include? key
        if !is_num?(value)
          errors.add(:base, "not numeric")
        end
      end
    end

    def is_num?(str)
      begin
        !!Integer(str)
      rescue ArgumentError, TypeError
        false
      end
    end

  end
end

app/controllers/admin/configuration_controller.rb
module Admin
  class ConfigurationController < ApplicationController
    #before_filter :authorize_tm

    def index
    end

    def calculate_num_tutors
      Course.recalculate_all_tutors!
      redirect_to request.env["HTTP_REFERER"], flash: { notice: "Successfully calculated the number of required tutors for all courses" }
    end

    def deadline
      if params[:date]
        if Admin::Configuration.deadline = params[:date]
          redirect_to request.env["HTTP_REFERER"], flash: { notice: "Updated deadline date" }
        else
          redirect_to request.env["HTTP_REFERER"], flash: { error: "Could not save deadline date" }
        end
        return
      end
      redirect_to request.env["HTTP_REFERER"], flash: { error: "Could not save deadline date" }
    end

    def tutor_hours
      if params[:hours]
        if Admin::Configuration.set_tutor_hours params[:hours]
          redirect_to request.env["HTTP_REFERER"], flash: { notice: "Updated hours per tutor" }
        else
          redirect_to request.env["HTTP_REFERER"], flash: { error: "There was an error updating the hours." }
        end
      else
        redirect_to request.env["HTTP_REFERER"]
      end
    end

    def course_hours
      required = ["100level", "200level", "300level", "400level"]
      if required.any?{|l| !params.include?(l) }
        redirect_to request.env["HTTP_REFERER"], flash: { error: "There was an error updating one or more parameter." }
      else
        error = false
        required.each do |level|
          unless Admin::Configuration.set_course_hours(level.slice(0,3), params[level])
            error = true
          end
        end

        if error
          redirect_to request.env["HTTP_REFERER"], flash: { error: "There was an error updating one or more parameter." }
        else
          redirect_to request.env["HTTP_REFERER"], flash: { notice: "Updated enrollment hours per course level." }
        end
      end
    end

    def year_and_term
      if params[:year] && params[:term]
        flashes = {notice: [], error: []}
        if Admin::Configuration.set_year params[:year]
          flashes[:notice] << "Successfully updated current year"
        else
          flashes[:error] << "Failed to update year"
        end
        if Admin::Configuration.set_term params[:term]
          flashes[:notice] << "Successfully updated current term"
        else
          flashes[:error] << "Failed to update term"
        end
        flashes.reject!{|k,v| v.empty?}
        flashes_out = {}
        flashes.map{|k,v| flashes_out[k] = v.join("<br />")}

        redirect_to request.env["HTTP_REFERER"], flash: flashes_out
      end
    end

    def import_courses
      # STUB, use the helper in admin/configuration_helper
    end

  end
end

app/helpers/admin/configuration_helper.rb
module Admin::ConfigurationHelper

	def import_courses
		# STUB import courses
	end
end

app/views/admin/configuration/index.html.erb
<h2>Actions</h2>
<div class="well">
  <div class="row">
    <div class="col-md-3">
      <h4>Year and term</h4>
      <%= form_tag admin_year_and_term_path, method: "post" do %>
        <div class='row'>
          <div class='col-md-4'>
            <%= text_field_tag "year", Admin::Configuration.year || Date.today.year, class: "form-control", placeholder: " Year", id: "current_year" %>
          </div>
          <div class='col-md-4'>
            <%= text_field_tag "term", Admin::Configuration.term || 1, class: "form-control", placeholder: " Term", id: "current_term" %>
          </div>
          <div class='col-md-4'>
            <input type='submit' class='btn btn-primary' id='currentyeartermsubmit' />
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <h4>Set semester's deadline</h4>
      <%= form_tag admin_deadline_path, method: "post" do %>
        <div class='row'>
          <div class='col-md-8'>
            <%= date_field_tag "date", Admin::Configuration.deadline || Date.today, class: "form-control", placeholder: "Date", id: "datepicker" %>
          </div>
          <div class='col-md-4'>
            <input type='submit' class='btn btn-primary' id='deadlinesubmit' />
          </div>
        </div>
      <% end %>


    </div>
    <div class="col-md-3">
      <h4>Course configuration</h4>
      <%= link_to "Calculate # Tutors", admin_calculate_tutors_required_path, class: "btn btn-primary" %>
    </div>
    <div class="col-md-2">
      <h4>Import Courses</h4>
      <%= link_to "Import Courses", admin_import_courses_path, method: "put", class: "btn btn-primary" %>
    </div>
  </div>
  <div class='row'>
    <div class="col-md-8">
      <h4>Set hours per enrollment per level</h4>
      <%= form_tag admin_course_hours_path, method: "post" do %>
      <div class='row'>
        <div class='col-md-2'>
          <%= label_tag "100 level" %>
          <%= text_field_tag "100level", Admin::Configuration.course_hours(100) || 0, class: "form-control", placeholder: "Hours per tutor" %>
        </div>
        <div class='col-md-2'>
          <%= label_tag "200 level" %>
          <%= text_field_tag "200level", Admin::Configuration.course_hours(200) || 0, class: "form-control", placeholder: "Hours per tutor" %>
        </div>
        <div class='col-md-2'>
          <%= label_tag "300 level" %>
          <%= text_field_tag "300level", Admin::Configuration.course_hours(300) || 0, class: "form-control", placeholder: "Hours per tutor" %>
        </div>
        <div class='col-md-2'>
          <%= label_tag "400 level" %>
          <%= text_field_tag "400level", Admin::Configuration.course_hours(400) || 0, class: "form-control", placeholder: "Hours per tutor" %>
        </div>
        <div class='col-md-2'>
          <%= submit_tag "Submit", class: "btn btn-primary", style: "margin-top:25px" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class="col-md-4">
      <h4>Set hours per tutor</h4>
      <%= form_tag admin_tutor_hours_path, method: "post" do %>
        <div class='row'>
        <div class='col-md-8'>
          <%= text_field_tag "hours", Admin::Configuration.tutor_hours || 0, class: "form-control", placeholder: "Hours per tutor" %>
        </div>
        <div class='col-md-4'>
          <%= submit_tag "Submit", class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  </div>
</div>