config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "configuration#index"
    get "/calculate_tutors_required" => 'configuration#calculate_num_tutors', as: 'calculate_tutors_required'

    post "/hourly_rates" => "hourly_rates#update", as: "hourly_rates_update"
    post "/deadline" => "configuration#deadline", as: "deadline"
    post "/tutor_hours" => "configuration#tutor_hours", as: "tutor_hours"
    post "/course_hours" => "configuration#course_hours", as: "course_hours"
    post "/year_and_term" => "configuration#year_and_term", as: "year_and_term"
    put  "/import_courses" => "configuration#import_courses", as: "import_courses"
    resources :hourly_rates, only: [:index] do
    end
  end

  get 'courses/:id/export_course' => 'courses#export_course', :as => 'export_course'
  get 'courses/export_all_courses' => 'courses#export_all_courses', :as => 'export_all_courses'
  patch 'courses/:id/calculate_tutors' => 'courses#calculate_required_tutors', as: 'calculate_required_tutors'
  patch 'courses/:id/propose_course' => 'courses#propose_course', as: 'propose_course'
  patch 'courses/:id/finalise_accepted' => 'courses#finalise_accepted', as: 'finalise_accepted'
  get "/courses/:id/get_no_required_tutors" => 'courses#get_no_required_tutors', as: 'required_tutors'
  resources :courses, only: [:index, :show, :update]

  get "login" => "sessions#new", :as => "login"
  post 'login' => 'sessions#create', :as => 'post_session'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'users#new', :as => 'signup'

  resources :users, :only => [:create, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  root "application#home_page"

  patch 'tutor_applications/:id/update_comment' => 'tutor_applications#update_comment', :as => 'update_comment'
  patch 'tutor_applications/:id/disqualify_tutor' => 'tutor_applications#disqualify_tutor', as: 'disqualify_tutor'

  get 'tutor_applications/:id/application_print' => 'tutor_applications#application_print', :as => 'print_application'
  get 'tutor_applications/export_finalised_tutors' => 'tutor_applications#export_finalised_tutors', :as => 'export_finalised_tutors'
  get 'tutor_applications/export_all_tutors' => "tutor_applications#export_all_tutors", :as => 'export_all_tutors'

  resources :tutor_applications, except: [:delete]
  get "/tutor_applications" => "tutor_applications#index", as: 'tutor_applications_filter'
  patch "/tutor_applications/:id/update_pay" => "tutor_applications#update_pay", as: 'tutor_application_update_pay'

  post "/allocation_link/:application_id" => "allocation_link#create", as: "create_allocation"
  put "/allocation_link/:id/update_state" => "allocation_link#update_state", as: "update_allocation_state"
  post "/accept/:id" => "allocation_link#accept", as: "accept_allocation"
  post "/reject/:id" => "allocation_link#reject", as: "reject_allocation"

  resources :allocation_link, only: [:destroy]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController


  #before_action :authorize_tm, only: [:update, :calculate_required_tutors, :export_course, :finalise_accepted]
  #before_action :authorize_tm_or_cc, only: [:index, :show, :propose_course]

  # CC and TM
  def index
    if current_user.TM?
      @courses = Course.all
    elsif current_user.CC?
      @courses = Course.where(course_coordinator_id: current_user.id)
    end
  end

  # CC and TM
  def show
    #Change view such that fields do not appear to be editible.
    @course = Course.find(params[:id])
    if !current_user.TM? && @course.course_coordinator_id != current_user.id
      redirect_to login_path, notice: "You are not authorized to view this page"
    end
    setup_course_show @course.id
  end

  # TM
  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      redirect_to course_path, :notice => "Successfully saved"
    else
      flash.now[:error] = "Not saved"
      render :show
    end
  end

  # TM
  def calculate_required_tutors
    @course = Course.find(params[:id])
    setup_course_show @course.id
    if @course.update(:tutors_required => @course.calculate_required_tutors)
      flash.now[:notice] = "Calculated required tutors"
      render :show
    else
      flash.now[:notice] = "Error calculating tutors"
      render :show
    end
  end

  def get_no_required_tutors
    @course = Course.where(id: params[:id]).first
    if @course && params[:enrol]
      render json: { value: @course.calculate_required_tutors_with_enroll(params[:enrol]) }
    else
      head status: 400
    end
  end

  # TM OR CC
  def propose_course
    if current_user.TM? #Update course state, and allocation states
      @course = Course.find(params[:id])
      @course.awaiting_cc!

      setup_course_show @course.id

      allocations = AllocationLink.awaiting.where(course_id: @course.id)
      allocations.each do |a|
        a.shortlisted!
      end

      redirect_to course_path(@course.id), flash: { notice: "Proposed Course" }
    elsif current_user.CC? #Update course state
      @course = Course.where(id: params[:id]).first
      if @course && @course.awaiting_cc? && current_user.id == @course.course_coordinator_id
        @course.awaiting_tm!
        redirect_to course_path(@course.id), flash: { notice: "Updated  course" }
      else
        redirect_to courses_path, flash: { error: "There was an error updating the specified course." }
      end
    end
  end

  # TM
  def finalise_accepted
    @course = Course.find(params[:id])
    if !@course.has_accepted?
      redirect_to course_path(@course), flash: { error: "There are no accepted tutors to finalise" }
      return
    end
    setup_course_show @course.id

    @allocations.accepted.each do |allocation|
      allocation.update(state: :allocated)
    end

    if @overallocated.empty?
      redirect_to course_path(@course), flash: { notice: "Moved accepted tutors to allocated state." }
    else
      redirect_to course_path(@course), flash: { notice: "Moved accepted tutors to allocated state. WARNING there are some people in this course tutoring more than 2 courses." }
    end
  end

  def export_all_courses
    courses = Course.all

    tempfile = Tempfile.new("test_all.xls")
    book = ExcelExport.export_all_courses courses
    book.write(tempfile.path)
    send_file tempfile.path, filename: "test_all.xls"
  end

  def export_course
    @course = Course.find(params[:id])

    tempfile = Tempfile.new("test.xls")
    book = ExcelExport.export_single_course(@course)
    book.write(tempfile.path)
    send_file tempfile.path, filename: "test.xls"
  end

  private

  def course_params
    params.require(:course).permit(:enrollment_number, :tutors_required, :state)
  end

  def setup_course_show(id)
    if current_user.TM?
      @allocations = AllocationLink.where(course_id: id)
    elsif current_user.CC?
      @allocations = AllocationLink.where(course_id: id, state: AllocationLink.cc_viewable_states)
    end

    allocations = AllocationLink.allocated.where(course_id: id)
    @overallocated = []
    allocations.each do |allocation|
      allocated_links = allocation.tutor_application.allocation_links.allocated
      @overallocated << allocation if allocated_links.size > 2
    end
  end
end

app/views/courses/_cc_details.html.erb
<strong>Number of Enrollments:</strong> <%= @course.enrollment_number %> <br>
<strong>Tutor's Required:</strong> <%= @course.tutors_required %> <br>
<br />
<%= render partial: "status_notification" %>
<% if @course.awaiting_cc? %>
  <div class='pull-right'>
    <%= link_to "Send updates to Tutor Manager", propose_course_path(@course.id), method: 'patch', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/_status_notification.html.erb
<% if !@course.dormant? %>
  <div class='alert alert-<%= @course.awaiting_colour(current_user) %>'>
    <%= @course.pp_state_for_user(current_user) %>
  </div>
<% end %>

app/views/courses/_tm_form.html.erb
<strong>Course Coordinator:</strong>
<% if @course.get_course_coordinator %>
  <%= link_to @course.get_course_coordinator.username, user_path(@course.get_course_coordinator) %> <br>
<% end %>
<%= semantic_form_for @course do |f| %>
  <%= f.inputs do %>
    <div class='row'>
      <div class='col-md-2'>
        <%= f.input :enrollment_number, label:  "Number of enrollments: "  %>
      </div>
      <div class='col-md-2'>
        <%= f.input :tutors_required, label:  "Tutors required: " %>
      </div>
      <div class='col-md-2'>
        <label class="control-label"></label>
        <%= link_to "Calculate required tutors", "#", class: "btn btn-default align-button", id: "calculate_tutors", data: { id: @course.id } %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-4'>
        <%= f.input :state, as: :select, :collection => Course.states.map{|str,val| [Course.pp_state(str), str] }, include_blank: false, label:  "State: "  %>
      </div>
      <div class='col-md-2'>
        <label class="control-label"></label>
        <%= f.actions do %>
          <%= f.action :submit, button_html: { class: "btn btn-primary align-button" } %>
        <% end %>
      </div>

    </div>
  <% end %>
<% end %>
<br />

<%= render partial: "status_notification" %>

app/views/courses/index.html.erb
<table class='table' id='table'>
  <thead>
    <tr>
      <th>Course Code</th>
      <th>Tutors Required</th>
      <th>Subtotal spent</th>
      <th>Tutors</th>
      <th>State</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr class='course_row' data-url='<%= course_path(course) %>'>
        <td><%= course.course_code %></td>
        <td><%= course.tutors_required %></td>
        <td><%= "$%.2f" % course.subtotal_spent %></td>
        <td>
          <% if (current_user.CC_or_TM? && !course.dormant?) || current_user.TM? %>
            <table>
              <tbody>
                <% course.allocation_links.where("state <> ?", AllocationLink.states[:unallocated]).each do |allocation_link| %>
                  <tr>
                    <td><%= allocation_link.tutor_application.full_name %> </td>
                    <td><%= number_to_currency allocation_link.tutor_application.pay_rate %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </td>
        <td class="<%= course.awaiting_colour(current_user) %>">
          <%= course.pp_state_for_user(current_user) %>
        </td>
        <td>
          <%= link_to "View", course_path(course), class: "btn btn-xs btn-primary" %>
          <%= link_to "Export", export_course_path(course), class: "btn btn-xs btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Export All Courses", :export_all_courses, class: "btn btn-xs btn-success" %>

app/views/courses/show.html.erb
<h2><%= "#{@course.name} - #{@course.course_code}" %></h2>

<p>
  <strong>Subtotal Spent:</strong> <%= "$%.2f" % @course.subtotal_spent %> <br>
  <%= render 'tm_form' if current_user.TM? %>
  <%= render 'cc_details' if current_user.CC? %>
</p>

<br />

<div class="row">
  <div class="col-md-7">
    <h4>Current allocations for this course</h4>
    <% if current_user.TM? && @course.has_accepted? %>
      <%= link_to "Finalise Accepted", finalise_accepted_path, class: 'btn btn-xs btn-success', :method => :patch %>
    <% end %>
    <% if current_user.TM? %>
      <%= link_to "Propose Course To Course Coordinator", propose_course_path, class: 'btn btn-xs btn-success', :method => :patch %>
    <% end %>
  </div>
</div>

<span>
  Red tutors are allocated to more than 2 courses.
</span>

<br />
<br />

<table class='table'>
  <thead>
    <th>Student Name</th>
    <th>Grade in course</th>
    <th>Suitability</th>
    <th>State</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @allocations.reject{|al| al.unallocated?}.each do |allocation| %>
      <tr class="<%= "overallocated" if @overallocated.include? allocation%>" data-url='<%= tutor_application_path(allocation.tutor_application) %>' id="allocation-row-<%= allocation.id %>">
        <td><%= "#{allocation.tutor_application.first_name} #{allocation.tutor_application.last_name}" %></td>
        <td><%= allocation.tutor_application.grade_for_course(allocation.course) %></td>
        <td>
          <span class='label label-<%= allocation.tutor_application.suitability_label_name_for_course(allocation.course) %>'>
            <%= allocation.tutor_application.suitability_name_for_course(allocation.course) %>
          </span>
        </td>
        <td>
          <%= render 'layouts/allocation_state', :allocation => allocation %>
        </td>
        <td>
          <%= link_to "View application", tutor_application_path(allocation.tutor_application), class: 'btn btn-xs btn-primary' %>
          <% if current_user.TM? %>
            <%= link_to "Deallocate", allocation_link_path(allocation), class: 'btn btn-xs btn-danger', method: :delete %>
          <% elsif current_user.CC? %>
            <!--  insert CC actions here -->
            <% if (allocation.shortlisted? || allocation.rejected?) && @course.awaiting_cc? %>
              <%= link_to "Accept application", accept_allocation_path(allocation), class: 'btn btn-xs btn-primary', :method => :post %>
            <% end %>
            <% if (allocation.shortlisted? || allocation.accepted?) && @course.awaiting_cc? %>
              <%= link_to "Reject application", reject_allocation_path(allocation), class: 'btn btn-xs btn-danger', :method => :post %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>