config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "configuration#index"
    get "/calculate_tutors_required" => 'configuration#calculate_num_tutors', as: 'calculate_tutors_required'

    post "/hourly_rates" => "hourly_rates#update", as: "hourly_rates_update"
    post "/deadline" => "configuration#deadline", as: "deadline"
    post "/tutor_hours" => "configuration#tutor_hours", as: "tutor_hours"
    post "/course_hours" => "configuration#course_hours", as: "course_hours"
    post "/year_and_term" => "configuration#year_and_term", as: "year_and_term"
    put  "/import_courses" => "configuration#import_courses", as: "import_courses"
    resources :hourly_rates, only: [:index] do
    end
  end

  get 'courses/:id/export_course' => 'courses#export_course', :as => 'export_course'
  get 'courses/export_all_courses' => 'courses#export_all_courses', :as => 'export_all_courses'
  patch 'courses/:id/calculate_tutors' => 'courses#calculate_required_tutors', as: 'calculate_required_tutors'
  patch 'courses/:id/propose_course' => 'courses#propose_course', as: 'propose_course'
  patch 'courses/:id/finalise_accepted' => 'courses#finalise_accepted', as: 'finalise_accepted'
  get "/courses/:id/get_no_required_tutors" => 'courses#get_no_required_tutors', as: 'required_tutors'
  resources :courses, only: [:index, :show, :update]

  get "login" => "sessions#new", :as => "login"
  post 'login' => 'sessions#create', :as => 'post_session'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'users#new', :as => 'signup'

  resources :users, :only => [:create, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  root "application#home_page"

  patch 'tutor_applications/:id/update_comment' => 'tutor_applications#update_comment', :as => 'update_comment'
  patch 'tutor_applications/:id/disqualify_tutor' => 'tutor_applications#disqualify_tutor', as: 'disqualify_tutor'

  get 'tutor_applications/:id/application_print' => 'tutor_applications#application_print', :as => 'print_application'
  get 'tutor_applications/export_finalised_tutors' => 'tutor_applications#export_finalised_tutors', :as => 'export_finalised_tutors'
  get 'tutor_applications/export_all_tutors' => "tutor_applications#export_all_tutors", :as => 'export_all_tutors'

  resources :tutor_applications, except: [:delete]
  get "/tutor_applications" => "tutor_applications#index", as: 'tutor_applications_filter'
  patch "/tutor_applications/:id/update_pay" => "tutor_applications#update_pay", as: 'tutor_application_update_pay'

  post "/allocation_link/:application_id" => "allocation_link#create", as: "create_allocation"
  put "/allocation_link/:id/update_state" => "allocation_link#update_state", as: "update_allocation_state"
  post "/accept/:id" => "allocation_link#accept", as: "accept_allocation"
  post "/reject/:id" => "allocation_link#reject", as: "reject_allocation"

  resources :allocation_link, only: [:destroy]

end

app/views/layouts/_allocation_state.html.erb
<div class="row">
  <div class="col-md-10">
    <% if current_user.TM? %>
      <%= semantic_form_for allocation, url: update_allocation_state_path do |f| %>
        <%= f.inputs do %>
          <%= f.input :state, as: :select, collection: AllocationLink.state_hash.invert, include_blank: false, label: false, input_html: { class: 'allocation-link-state', data: { id: allocation.id }} %>
        <% end %>
      <% end %>
    <% else %>
      <%= allocation.readable_state %>
    <% end %>
  </div>
  <div class="col-md-2">
    <span class="alloc-update-status" id="alloc-update-status-<%= allocation.id %>">
      
    </span>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#tutor-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tutor Allocation" , root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="tutor-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown <%= "active" if active_controller?(controller_name, "tutor_applications") %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tutor Applications <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li><%= link_to "New Application", new_tutor_application_path %></li>
              <% if current_user && current_user.TM? %>
                <li><%= link_to "All Applications", tutor_applications_path %></li>
              <% end %>
          </ul>
        </li>
        <% if current_user && (current_user.TM? || current_user.CC?) %>
          <li class="<%= "active" if active?(request.path, courses_path)  %>" >
            <%= link_to "Courses", courses_path %>
          </li>
        <% end %>
        <% if current_user && current_user.TM? %>
          <li class="dropdown <%= "active" if (active_namespace?(controller, "Admin")) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><%= link_to "General Configuration", admin_root_path %></li>
                <li><%= link_to "Hourly Rates", admin_hourly_rates_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if active?(request.path, login_path)  %>">
          <%= link_to "Log in", login_path %>
        </li>
        <li class="<%= "active" if active?(request.path, signup_path)  %>">
          <%= link_to "Sign up", signup_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaceholderTutorAllocation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller_name %>" class="<%= action_name %>">
<div class="container">
  <%= render 'layouts/navbar' %>
  <% if current_user.present? %>
    <span class='pull-right'>You are logged in as <%= current_user.username %> (<%= current_user.role %>)</span>
  <% end %>
  <%= image_tag "vuw-logo.png", class: "vuw-logo-large-centered"%>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, raw(msg), :class => "alert alert-#{alert_string(name)}" %>
  <% end %>

  <%= yield %>
</div>


</body>
</html>